### ISSUE TITLE
Enhancement: Allow configuration using system properties

### ISSUE THREAD

**Issue by domkun** [chkal/gitlab-code-quality-plugin#5]
As I am using the plugin in a GitLab CI/CD component it is sometimes useful to execute the plugin without any changes to the `pom.xml`.

The possibility to configure the plugin using system properties would be great to have.

**Comment by chkal** [comment]
Fixed via #6. Thanks a lot for your help. I'll try to find some time over the weekend to publish a new release!

**Comment by chkal** [comment]
I just released version 1.1.0 to Maven Central. It may take a few hours for the release to show up there.

Thanks again for your help!

**Comment by domkun** [comment]
Thanks a lot for your effort. Glad I could Help.
