### ISSUE TITLE
No report if all checkstyle issues are fixed

### ISSUE THREAD

**Issue by r3ps4J** [chkal/gitlab-code-quality-plugin#7]
Hi! Thanks for this plugin, it works great.

If there are no checkstyle issues left, there is no report generated anymore. This way it doesn't show anymore that x amount of problems were fixed in a certain merge request, nor does it show a check with the code quality report.

This is what I had before:

![image](https://github.com/user-attachments/assets/36cc991d-9434-4f3e-b014-e1ba88426adf)

And when I fixed the last issue, that box disappeared. This is the log from my pipeline:

```
[INFO] SpotBugs report not found: /builds/<repository redacted>/target/spotbugsXml.xml
[INFO] Checkstyle report with 0 issues found: /builds/<repository redacted>/target/checkstyle-result.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.911 s
[INFO] Finished at: 2024-10-23T18:24:48Z
[INFO] ------------------------------------------------------------------------
...
Uploading artifacts for successful job 00:00
Uploading artifacts...
WARNING: target/gl-code-quality-report.json: no matching files. Ensure that the artifact path is relative to the working directory (/builds/<repository redacted>) 
ERROR: No files to upload                          
Cleaning up project directory and file based variables 00:01
Job succeeded
```

I've fixed it myself now by adding a script which creates an empty report so I get that box again, but I think this is something that should be done by the plugin either way. Or perhaps through a configuration variable.
```bash
if [ ! -f "$REPORT_PATH" ]; then
  mkdir -p "$(dirname "$REPORT_PATH")"
  echo "[]" > "$REPORT_PATH"
  echo "Created an empty $REPORT_PATH"
fi
```

**Comment by chkal** [comment]
Good catch! I guess that I never noticed as we never got rid of all the findings. :-)

But yes, I think it makes sense to fix this. Will do so in the upcoming days.

**Comment by chkal** [comment]
The issue was just fixed. Could you perhaps give `1.2.0-SNAPSHOT` and confirm the fix? Details about how to use the latest snapshots can be found in the README.
